title: Diego Aguilera # your name (or website title) here
logo: "/images/IMG_1648.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Analyzing data to asnwer questions 
  Make it makes sense  <br><br>
  <a href="https://www.linkedin.com/in/aguileradjc/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
